version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "00:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 99
    assignees:
      - klane
    labels:
      - dependencies
      - ruby
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 99
    assignees:
      - klane
    labels:
      - dependencies
      - actions
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "00:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 99
    assignees:
      - klane
    labels:
      - dependencies
      - python
