version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"
      - "python"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: "ruby:bundler"
    directory: "/docs"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"
      - "ruby"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: "github_actions"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
      - "actions"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
